//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wangyou.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class bk_users
    {
        public int userid { get; set; }
      
        public string u_name { get; set; }
        [Display(Name ="密码")]//数据注解
        [Required(ErrorMessage = "{0}必须填写！")]//必填验证
        [DataType(DataType.Password)]//数据类型设为密码型
        public string u_pwd { get; set; }
        [Display(Name = "邮箱")]
        [Required(ErrorMessage = "{0}必须填写！")]
        public string u_email { get; set; }
       
        public Nullable<System.DateTime> logintime { get; set; }

    }
}
