//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class bk_users
{
    public int userid { get; set; }
    public string u_name { get; set; }
    public string u_pwd { get; set; }
    public string u_email { get; set; }
}

public partial class WanZhangType
{
    public WanZhangType()
    {
        this.WenZhang = new HashSet<WenZhang>();
    }

    public int WenZhangTypeID { get; set; }
    public string WenZhangTypeNmae { get; set; }

    public virtual ICollection<WenZhang> WenZhang { get; set; }
}

public partial class WenZhang
{
    public int wenzhangID { get; set; }
    public string wenzhangBiaoTI { get; set; }
    public string wenzhangContent { get; set; }
    public string wenzhangImg { get; set; }
    public int wenzhangTypeID { get; set; }
    public System.DateTime wenzhangDateTime { get; set; }
    public string wenzhangHTML { get; set; }

    public virtual WanZhangType WanZhangType { get; set; }
}
