//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class WangYouBKEntities : DbContext
{
    public WangYouBKEntities()
        : base("name=WangYouBKEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<bk_users> bk_users { get; set; }
    public DbSet<WanZhangType> WanZhangType { get; set; }
    public DbSet<WenZhang> WenZhang { get; set; }
}
